---
title: "Web Scraping 2"
author: "RO e VJT"
date: "15 de julho de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[comment]: # (http://www.computerworld.com/article/2971265/application-development/how-to-drive-a-web-browser-with-r-and-rselenium.html)

```{r, p1, echo=FALSE, eval=FALSE}
# https://yihui.name/en/2010/10/grabbing-tables-in-webpages-using-the-xml-package/
if (!require(XML)) install.packages('XML')

library("RSelenium");

url <- "http://www2.bmf.com.br/pages/portal/bmfbovespa/lumis/lum-ajustes-do-pregao-ptBR.asp";

# Abre o navegador
driver <- rsDriver();
mybrowser <- driver[["client"]];
mybrowser$navigate(url);

# Campo
wxbox <- mybrowser$findElement(using='css selector', "#dData1");
wxbox$clearElement();
wxbox$sendKeysToElement( list("11/07/2017") );

# Botão
wxbutton <- mybrowser$findElement(using='css selector', ".expand");
wxbutton$clickElement();

library("XML");

teste2 <- htmlParse( mybrowser$getPageSource()[[1]], encoding = "iso-8851-1" );
teste2a <- readHTMLTable(teste2);
teste2a

# Fecha o navegador
mybrowser$close();
```


```{r}
library("RSelenium");

url <- "http://www2.bmf.com.br/pages/portal/bmfbovespa/lumis/lum-ajustes-do-pregao-ptBR.asp";

# Abre o navegador
driver <- rsDriver(port=4444L);
mybrowser <- driver[["client"]];
mybrowser$navigate(url);

elem <- mybrowser$findElement(using="id", value="tblDadosAjustes");
elemtxt <- elem$getElementAttribute("outerHTML")[[1]];

library("XML");
elemtxt <- xmlTreeParse(elemtxt, useInternalNodes=T)

lala <- getNodeSet(elemtxt, "//td")

as.character(lala[[1]])

thepage <- sapply(thepage, xmlValue)

# sub(".*?(&.*?);.*", "\\1", str1) para arrumar o banco dps

xmlValue(lala[[1]])

```


```{r, p3, echo=FALSE, eval=TRUE}
# Pega o XML do site correspondente à tabela com os dados
webTabela <- grep(pattern="<td", x=thepage, value=TRUE);

# Cria uma tabela com os dados
possiveisMercadorias <- seq(from=1, to=length(webTabela), by=6);
TabelaDados <- NULL;
for(ii in possiveisMercadorias){
  candidataMercadoria <- sub(pattern=".*<td>", replacement="", x=webTabela[ii]);
  candidataMercadoria <- sub(pattern=" *</td>$", replacement="", x=candidataMercadoria);
  
  if(candidataMercadoria!=""){
    Mercadoria <- candidataMercadoria;
  }
  webLinhaDados <- webTabela[(ii+1):(ii+5)];
  LinhaDados <- sub(pattern=".*\">", replacement="", x=webLinhaDados);
  LinhaDados <- sub(pattern=" </td>$", replacement="", x=LinhaDados);
  LinhaDados <- sub(pattern="</td>$", replacement="", x=LinhaDados);
  LinhaDados <- data.frame( t( c(Mercadoria, LinhaDados) ) );
  
  TabelaDados <- rbind(TabelaDados, LinhaDados);
}

# TabelaDados <- cbind(TabelaDados, atualizadoEm);

# names(TabelaDados) <- Titulos;
```



