---
title: "Web Scraping 1"
author: "RO e VJT"
date: "15 de julho de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Falta fazer

Automatizar a coleta de dados de datas anteriores

Up1: Já consigo navegar na página, acessando datas anteriores, mas preciso ver como pegar os dados com o novo pacote. Ver WebScraping2

[comment]: # (http://www.bmfbovespa.com.br/pt_br/servicos/market-data/historico/mercado-de-derivativos/ajustes-do-pregao/)

```{r, p1, echo=FALSE, eval=TRUE}
library("XML");

# Endereço da página com os dados
url <- "http://www2.bmf.com.br/pages/portal/bmfbovespa/lumis/lum-ajustes-do-pregao-ptBR.asp";

# XML da página com os dados
thepage <- readLines(con=url, warn=FALSE);

# Outra opção:
# teste1 <- readHTMLTable(doc=url, encoding = "iso-8859-1");
# Mas tem problema de enconding
```

```{r, p1_1, echo=FALSE, eval=TRUE}
# Pega a data em que os dados foram atualizados
webAtualizadoEm <- grep(pattern="<br />Atualizado", x=thepage, value=TRUE);
atualizadoEm <- sub(pattern=".*: ", replacement="", x=webAtualizadoEm);
```

```{r, p2, echo=FALSE, eval=TRUE}
# Pega os nomes das colunas da tabela
webTitulos <- grep(pattern="<th ", x=thepage, value=TRUE);
Titulos <- sub(pattern=".*\">", replacement="", x=webTitulos);
Titulos <- sub(pattern="</th>$", replacement="", x=Titulos);
Titulos <- c(Titulos, "Data Atualização");
```

```{r, p3, echo=FALSE, eval=TRUE}
# Pega o XML do site correspondente à tabela com os dados
webTabela <- grep(pattern="<td", x=thepage, value=TRUE);

# Cria uma tabela com os dados
possiveisMercadorias <- seq(from=1, to=length(webTabela), by=6);
TabelaDados <- NULL;
for(ii in possiveisMercadorias){
  candidataMercadoria <- sub(pattern=".*<td>", replacement="", x=webTabela[ii]);
  candidataMercadoria <- sub(pattern=" *</td>$", replacement="", x=candidataMercadoria);
  
  if(candidataMercadoria!=""){
    Mercadoria <- candidataMercadoria;
  }
  webLinhaDados <- webTabela[(ii+1):(ii+5)];
  LinhaDados <- sub(pattern=".*\">", replacement="", x=webLinhaDados);
  LinhaDados <- sub(pattern=" </td>$", replacement="", x=LinhaDados);
  LinhaDados <- sub(pattern="</td>$", replacement="", x=LinhaDados);
  LinhaDados <- data.frame( t( c(Mercadoria, LinhaDados) ) );
  
  TabelaDados <- rbind(TabelaDados, LinhaDados);
}

TabelaDados <- cbind(TabelaDados, atualizadoEm);

names(TabelaDados) <- Titulos;
```

```{r, p4, echo=FALSE, eval=TRUE}
# Grava os dados num arquivo csv
atualizadoEm2 <- gsub(pattern="/", replacement="_", x=atualizadoEm);

arquivoNome <- paste("derivativos_ajuste_", atualizadoEm2, ".csv", sep="");

write.csv2(x=TabelaDados, file=arquivoNome, row.names=FALSE);
```

# Tabela

```{r, p5, echo=FALSE, eval=TRUE, results="as.is"}
# Verifica se a tabela foi criada com sucesso
library("knitr");
kable( x=TabelaDados[c(1:10, 182:192), ] );
```



```{r, p6, echo=FALSE, eval=FALSE}
# Tabela com as mercadorias do dia
webTabelaMercadoria <- grep(pattern="<td>[A-Z]", x=thepage, value=TRUE);
TabelaMercadoria <- sub(pattern=".*<td>", replacement="", x=webTabelaMercadoria);
TabelaMercadoria <- sub(pattern=" *</td>$", replacement="", x=TabelaMercadoria);
TabelaMercadoria[1:20];
```
